---
inherit_gem:
  rubocop-github:
  - config/default.yml # generic Ruby rules and cops
require:
  - rubocop-rspec

RSpec/ExampleLength:
  Exclude:
    - spec/lib/samvera/graph_ql/client_spec.rb
    - spec/lib/samvera/owner_spec.rb
    - spec/lib/samvera/project_spec.rb
    - spec/lib/samvera/team_spec.rb

RSpec/MultipleExpectations:
  Exclude:
    - spec/lib/samvera/issue_spec.rb
    - spec/lib/samvera/label_spec.rb
    - spec/lib/samvera/owner_spec.rb
    - spec/lib/samvera/project_spec.rb
    - spec/lib/samvera/graph_ql/client_spec.rb
    - spec/lib/samvera/ruby_gems/client_spec.rb
    - spec/lib/samvera/team_spec.rb
    - spec/lib/samvera/repository_spec.rb

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/lib/samvera/issue_spec.rb
    - spec/lib/samvera/label_spec.rb
    - spec/lib/samvera/owner_spec.rb
    - spec/lib/samvera/project_spec.rb
    - spec/lib/samvera/graph_ql/client_spec.rb
    - spec/lib/samvera/ruby_gems/client_spec.rb
    - spec/lib/samvera/repository_spec.rb
    - spec/lib/samvera/team_spec.rb

RSpec/NestedGroups:
  Exclude:
    - spec/lib/samvera/graph_ql/client_spec.rb
